package com.example.backend.entities.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;

/**
 * DTO for quick rule validation check results
 * Used for fast overview of rule performance and activity status
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Schema(description = "Quick rule validation check response containing basic rule performance metrics")
public class QuickRuleCheckDTO {

    @Schema(description = "Unique rule identifier", example = "1001")
    private Integer ruleId;

    @Schema(description = "Human-readable rule name", example = "High Amount Transfer Rule")
    private String ruleName;

    @Schema(description = "Number of recent alerts generated by this rule", example = "15")
    private Integer recentAlerts;

    @Schema(description = "Rule credibility score (0-100)", example = "85")
    private Integer credibilityScore;

    @Schema(description = "Date of the last alert generated by this rule", example = "2024-01-15")
    private LocalDate lastActivityDate;

    @Schema(description = "Whether the rule is currently active (generating alerts)", example = "true")
    private Boolean isActive;
}
